# -*- coding: utf-8 -*-
"""simpleMovingAverage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kb12hxjiH6T-T6o95SiKhAjjHATWV8wJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

y_train = pd.read_csv("../data/y_train_HNMbC27.csv")
y_train_correlation_plot_data = y_train.iloc[:,1:]

y_train_correlation_plot_data.head(5)

#get number of coumns and store
cols = len(y_train_correlation_plot_data.columns)
print(cols)

#therefore the number of columns in the dataframe to plot should be cols/3
i = 0
list_of_plot_columns =[]
while(i<=(cols-2)):
  colname = y_train_correlation_plot_data.columns[i]
  colname_new = colname.rsplit('_', 1)[0]
  list_of_plot_columns.append(colname_new)
  i2 = y_train_correlation_plot_data.columns[i+1]
  i3 = y_train_correlation_plot_data.columns[i+2]
  y_train_correlation_plot_data[colname_new]=(y_train_correlation_plot_data[colname]+y_train_correlation_plot_data[i2]+y_train_correlation_plot_data[i3])/14
  i= i+3

print(len(list_of_plot_columns))

y_train_correlation_plot_data = y_train_correlation_plot_data.reset_index()

y_train_correlation_plot_data.head(5)



for item in list_of_plot_columns:
  plot_c = y_train_correlation_plot_data.plot(x='index', y=[item] ,figsize=(100,50), grid=True)
  fig = plot_c.get_figure()
  fig.savefig("../plots/data/output"+item+".png")
#fig, ax = plt.subplots()
#x = range(cols)
#ax.stackplot(x, *[y_train_correlation_plot_data[col] for col in ['Diff_VIX', 'Diff_MOVE']])
#plot.show()
